---
  - name: Install and launch Filebeat
    hosts: webservers
    become: true
    tasks:

    - name: Download Filebeat install file
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    - name: Install Filebeat program
      command: dpkg -i filebeat-7.4.0-amd64.deb  

    - name: Copy Filebeat config file
      copy:
        src: /etc/ansible/files/filebeat-config.yml 
        dest: /etc/filebeat/filebeat.yml

    - name: Enable Filebeat system modules
      command: filebeat modules enable system

    - name: Setup Filebeat 
      command: filebeat setup

    - name: Startup Filebeat 
      command: service filebeat start

    - name: Enable filebeat service
      systemd:
        name: filebeat
        enabled: yes
